apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - uname
              #  - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
          #["-c", "while true; do echo hello; sleep 10;done"]
