apiVersion: v1
kind: Pod
metadata:
  name: four-containers
spec:

  restartPolicy: Never

  containers:

  - name: nginx-container
    image: nginx
    stdin: true
    tty: true

  - name: redis-container
    image: redis
    stdin: true
    tty: true

  - name: memcached-container
    image: memcached
    stdin: true
    tty: true

  - name: consul-container
    image: consul
    stdin: true
    tty: true

