apiVersion: v1
kind: Pod
metadata:
  name: radis-pod
  namespace: web
spec:
  containers:
  - image: redis
    name: radis
    ports:
    - name: http
      containerPort: 8080
  restartPolicy: OnFailure

